### ISSUE TITLE
Add timeout or browser verification when using -interactive

### ISSUE THREAD

**Issue by bjompen** [PalmEmanuel/AzAuth#12]
When running Get-AzToken with the -Interactive switch, if no login is performed and the browser window is closed, the command seems to hang.

**Steps to reproduce**

Make sure no active sessions are available
Run
```PowerShell
Get-AzToken -Interactive 
```

Close the opened browser window without logging in.

**Expected behaviour**

If possible, I would prefer the command to either simply stop, or return an error (no account logged on or similar, something we can catch in a catch block)
If not, at least a timeout of n+1 seconds before throwing an error to prevent pipelines from hanging.

**Comment by PalmEmanuel** [comment]
It doesn't seem like there's a built-in timeout function, but I'll add a way to configure it using the provided cancellationtoken to the method. Thanks for the report!
