### ISSUE TITLE
Use token to connect to MS Exchange Online

### ISSUE THREAD

**Issue by GamerClassN7** [PalmEmanuel/AzAuth#25]
Hello, 

when using Get-MsalToken  from deferent module i am able to connect to whit token to Exchange online powershell
how ever when using more robust Get-AzToken from this module i am not able to connect even that i am passing correct resource url https://outlook.office365.com/ 

Is there anybody who was able to connect successfully to EXO ?

**Comment by PalmEmanuel** [comment]
Hi and thanks for the reported issue!

Do you have any code to reproduce the issue that I can have a look at?

**Comment by GamerClassN7** [comment]
Hello @PalmEmanuel ,

![image](https://github.com/PalmEmanuel/AzAuth/assets/22167469/3d2b950b-ec2f-437e-9c7a-af5695a48814)
![image](https://github.com/PalmEmanuel/AzAuth/assets/22167469/09cb59e6-57d6-4540-8ac7-032136c1dc3c)
whitch results in 
![image](https://github.com/PalmEmanuel/AzAuth/assets/22167469/ef460eab-63e5-4425-8ea7-4bfe86ce6594)

how ever when i request token threw : MSAL
![image](https://github.com/PalmEmanuel/AzAuth/assets/22167469/a2889254-e670-458b-8545-2da6cfe7387a)

i am able to connect just fine.

From my understanding both modules should utilize MSAL.net in background, so it should be possible to acquire token wia get-aztoken but for some reasons it is not, I would rather sticked to this simple yet powerful module rather than use now archived MSALPS


Thanks for your time and effort.

**Comment by PalmEmanuel** [comment]
Unfortunately I don't have an Exchange environment available to test with, but when I compare AzAuth and MSAL.PS I seem to get equivalent tokens when [inspecting them](https://jwt.ms/). What are you using for splatting to get the token through MSAL.PS in `$connectorArguments` (without sharing anything sensitive, of course)?

I tried the following:
```powershell
$AzAuthToken = Get-AzToken -Resource 'https://outlook.office365.com/' -Interactive

# I'm using the client id for Azure CLI, and .default as scope, same as AzAuth does by default
$MsalPsToken = Get-MsalToken -Interactive -ClientId "04b07795-8ddb-461a-bbee-02f9e1bf7b46" -Scopes 'https://outlook.office365.com/.default'
```

An obvious difference to me is how to specify scope, I decided to split `-Resource` and `-Scope` for AzAuth and default to `.default` for the scope and Azure CLI for the client being used, but the commands otherwise seem to give me tokens of equal access (user_impersonation).

Try it and let me know if you find any differences still, and if you're using any specific client or otherwise when using MSAL.PS. As you say, AzAuth should absolutely be fine to use here as well.

**Comment by GamerClassN7** [comment]
Hello,
when decoding JWT created ony diference i can see are scopes
![image](https://github.com/PalmEmanuel/AzAuth/assets/22167469/050c645b-41e4-4cc6-bc51-b509e9585dce)
The first value is from MSAL second From AzAuth.
![image](https://github.com/PalmEmanuel/AzAuth/assets/22167469/ab7127d8-1d14-4cb7-81e6-8b4abb26f00f)
I am using internal client ID. But even with use of same client id for azure cli i still get invalid token just with "user_impersonation" Scope  so i guess problem will be somewhere where is  scope handled by AZModule ?

**Comment by PalmEmanuel** [comment]
If you're using an internal client id and specifying tenant, you will need to do the same in AzAuth.

Is there a difference if you try this?

```powershell
$ConnectorArguments = @{
    ClientId = '<your-client-id>'
    Resource = 'https://outlook.office365.com/'
    TenantId = '<your-tenant-id-or-url>'
    Scope = '.default' # this is the default, but I added it for clarification
    Interactive = $true
}
$AzAuthToken = Get-AzToken @ConnectorArguments
```

**Comment by GamerClassN7** [comment]
> s there a difference if you try this

No it is exactly the same

**Comment by GamerClassN7** [comment]
But scopes returned are difrent for some reason

**Comment by PalmEmanuel** [comment]
Are you able to get the right token if you specify those scopes?

$ConnectorArguments = @{
    ClientId = '<your-client-id>'
    Resource = 'https://outlook.office365.com/'
    TenantId = '<your-tenant-id-or-url>'
    Scope = 'AdminApi.AccessAsUser.All FfoPowerShellAccessAsUser.All RemotePowerShell.AccessAsUser.All '
    Interactive = $true
}
$AzAuthToken = Get-AzToken @ConnectorArguments

**Comment by GamerClassN7** [comment]
I will get error thati need concent of ORG is required whit is not the case for MSAL

**Comment by PalmEmanuel** [comment]
Just to verify, you still get that error if you specify ClientId with `Get-AzToken`?

**Comment by GamerClassN7** [comment]
Yes, i tryed both my Internal app ID and suggested azure-cli, BTW if you want we can connect over for example discord not to spam you issues :)

**Comment by PalmEmanuel** [comment]
Absolutely, I can message you there. What's your Discord?

**Comment by GamerClassN7** [comment]
just a jonatanrek

**Comment by PalmEmanuel** [comment]
The issue was that the Interactive authentication method did not properly use the provided Client Id, it always used the default Azure CLI client.
