### ISSUE TITLE
Failed to refresh token with multiple caches

### ISSUE THREAD

**Issue by GamerClassN7** [PalmEmanuel/AzAuth#26]
Recreantly i start getting this error when trying to use 2 different named cashes at once
![image](https://github.com/PalmEmanuel/AzAuth/assets/22167469/b3988b93-d3c6-4924-887b-b2630890a152)

First cash always  works correctly second one almost never. :(

**Comment by GamerClassN7** [comment]
Interesting it happens only when trying to reuse token for Exchange Online we troubleshoot Last time

**Comment by PalmEmanuel** [comment]
Can you give an example of code that uses different caches at once, to reproduce the issue?

**Comment by GamerClassN7** [comment]
First one 
![image](https://github.com/PalmEmanuel/AzAuth/assets/22167469/b13e4bab-d73f-4c56-a1e8-e9f7918cdbd3)
second one (always works)
![image](https://github.com/PalmEmanuel/AzAuth/assets/22167469/fe8017fd-de14-4320-8424-ca1a30d07262)

**Comment by GamerClassN7** [comment]
Could this be related to different client ID ?

**Comment by PalmEmanuel** [comment]
Are you running these in order, in the same powershell session?

**Comment by GamerClassN7** [comment]
Yes 
First is azure then exo

**Comment by PalmEmanuel** [comment]
You don't need to create different caches for them. I will look into the problem with different caches, but once you've gotten a token you should be able to get another with the same cache for another resource, so this isn't a necessary pattern for scripts or same-session work.

**Comment by GamerClassN7** [comment]
Ok, Good to know :)

**Comment by PalmEmanuel** [comment]
I'll create a separate issue on improving the documentation with examples to reduce possibly confusion with how to use the module 👍

**Comment by GamerClassN7** [comment]
> Ok, Good to know :)

actually just verified that i need to use different cache name otherwise i am not able to connect to EXO at all since i always get token with scopes of AAD token

**Comment by PalmEmanuel** [comment]
Are you specifying the correct resource and scopes when getting the token the second time?

**Comment by GamerClassN7** [comment]
> Are you specifying the correct resource and scopes when getting the token the second time?
> 
> By default, the token will be for Graph.

Hmm actually that could be the case

**Comment by GamerClassN7** [comment]
Hello @PalmEmanuel,
you were right as you can see on my screens. i did not understanded how AzAuth cache mechanic works. and forgot to include Resource  on first load in try part of both functions and since graph resource is the default  graph api token always worked. mastery resolved :D

**Comment by PalmEmanuel** [comment]
Happy to hear that!

**Comment by GamerClassN7** [comment]
Hmm.... issue seems prevailing but not so often 
![image](https://github.com/PalmEmanuel/AzAuth/assets/22167469/3c912bb5-9346-476b-a500-f72fca43070c)
once in while i get this error 🆙 

But if i run script again no authentication nothing is needed and everything works as expected

**Comment by PalmEmanuel** [comment]
Can you post the code (or most of it) and describe when you see the error? Are you working with one or multiple caches, and is it in the same or different PowerShell sessions?

**Comment by GamerClassN7** [comment]
Unfortunately the code is quiet wast.
Multiple cashes name the same session


But not doing something extra special.
Just calling the exchange online API in 2 minute loop with get-exomailbox.

**Comment by PalmEmanuel** [comment]
Can you describe the order of commands you're using, or some type of pseudo-code?

For example:
1. `Get-AzToken -Interactive -TokenCache 'MyCache1'`
2. `Get-AzToken -TokenCache 'MyCache1'`
3. `Get-AzToken -DeviceCode -TokenCache 'MyCache2' -Resource 'https://outlook.office.com'`
4. `Get-AzToken -TokenCache 'MyCache2' -Resource 'https://outlook.office.com'`

If it's in the same session, the module does its best to keep the authentication record for interactive authentications so that you don't need to specify cache, which I'm suspecting may cause the problems here, but I need some more understanding to be able to verify. Also, are you using any parallelization, such as `ForEach-Object -Parallel`?

**Comment by GamerClassN7** [comment]
`Get-AzToken -TokenCache 'MyCache1' -Resource 'https://outlook.office.com' -ClientID '' -Username ''` - Is most fitting

hoever i think i found the root cause when token is returned from cache is not refreshed even when 
![image](https://github.com/PalmEmanuel/AzAuth/assets/22167469/7d768e56-74e6-415d-ad20-d3b00615d5e4)
is many minutes in past: 
![image](https://github.com/PalmEmanuel/AzAuth/assets/22167469/b1562183-648f-4245-a8ae-534a9b964704)
souled be token refreshed on return from cash if is expired ? could this be the issue ?

**Comment by PalmEmanuel** [comment]
I don't see any immediate issue with the code. Maybe you could run Get-Error of the `Failed to refresh access token` error and give me the full stack trace?

I would also like to know in which order you get the tokens, not just the one where it fails. First you have to get it interactively and save it as a token somewhere, that's what I was requesting with the pseudocode.

**Comment by GamerClassN7** [comment]
Token get order:
1. Graf API token
2. Exchange token

i am trying to to implement this  workeround:
![image](https://github.com/PalmEmanuel/AzAuth/assets/22167469/cd9873c3-df48-4319-a199-75687aaaf248)

**Comment by PalmEmanuel** [comment]
I'm having trouble replicating the issue. The problem with the above code is that you catch all possible errors that might happen the first time you try to get a token, and get a new one interactively instead. It would be useful to see more information about your errors.

To understand the scenario, I think you will need to give me some pseudo-code or at least the steps involved with the different parameters. I only need to understand the order of your `Get-AzToken` commands and if they are interactive, or different caches.

If it's a lot of code, can you give me a full order in something like this? I mainly need to understand which order you use the module and how.

> First session:
> 1. Get Graph token interactively, save in Cache1
> 2. Get Outlook token interactively, save in Cache2
> 3. Get users with Outlook token
> 4. For each user, do something for user
> 5. etc etc
> 
> In a new session:
> 1. Get Graph token from Cache1
> 2. Get Outlook token from Cache2
> 3. For each user, do something...
>

Unless I get a better understanding of the order that you're getting the tokens and using the cache(s), I'm not sure I can replicate it and fix it if it's a bug.

**Comment by GamerClassN7** [comment]
> Another way to go about it is if you can describe your process and what you're trying to achieve with your solution / script, in that case I can suggest how I would get tokens, and you can compare to see what you've implemented.

HI, sorry for later reply i just simply implemented workaround that i manually check, that if token is expired, i just manually run auth function again and it work :)
