### ISSUE TITLE
Module can't be imported on Azure Functions using Linux runtime.

### ISSUE THREAD

**Issue by bjompen** [PalmEmanuel/AzAuth#30]
When trying to import the module on an Azure Function using Linux runtime there is a dll loading error.

Runtime is PowerShell ~4, host is Linux. I have not tried on other runtimes.

>   "PSVersion": {
>   "Major": 7,
>    "Minor": 2,
>   "Patch": 13,
>   "PreReleaseLabel": null,
>    "BuildLabel": null
>  },

![image](https://github.com/PalmEmanuel/AzAuth/assets/17783007/5212f96f-b4cb-402c-a51e-bbe25a018a57)

![image](https://github.com/PalmEmanuel/AzAuth/assets/17783007/5f1e3070-8444-4d26-8b21-25dbf9d8f448)

**Comment by PalmEmanuel** [comment]
Solved in 2.2.5 by #35
