### ISSUE TITLE
EXO authentication stopped working since friday

### ISSUE THREAD

**Issue by GamerClassN7** [PalmEmanuel/AzAuth#65]
When using token to authenticate i get this error:
![image](https://github.com/PalmEmanuel/AzAuth/assets/22167469/6013c8f2-09cc-4b51-a71b-57dcd2d71aa8)
when using token from your module -> if i leave authentication on EXO module alone it works without an issue, how ever this is not usable for my scenario :/ Could i ask you please to take a look in to this issue ?

**Comment by PalmEmanuel** [comment]
Hi, sorry to hear that you're having issues. Can you post the code you're using for getting the token? I don't use the EXO module myself, but it would also be useful to understand which scopes and resources the token is issued for.

**Comment by GamerClassN7** [comment]
> Hi, sorry to hear that you're having issues. Can you post the code you're using for getting the token? I don't use the EXO module myself, but it would also be useful to understand which scopes and resources the token is issued for. 

Nothing special, 😔  and token is squired correctly but when passed to EXO module I get the error above almost like API did no decoded the JWT or something...
`#$token = Get-DWSSExchangeOnlineAuthentication
Connect-ExchangeOnline -ShowBanner:$false #-AccessToken $token.Token -UserPrincipalName $token.Identity`

**Comment by PalmEmanuel** [comment]
Does it work with a token from another module? In that case, can you use a service like jwt.ms and show me that token and one from AzAuth (without sensitive data) for comparison?

**Comment by PalmEmanuel** [comment]
It's Microsofts decoder for JWTs: https://jwt.ms/

**Comment by GamerClassN7** [comment]
> It's Microsofts decoder for JWTs: https://jwt.ms/
> 
> There are also other services or libraries like jwt.io so which one you use is completely up to you.

OK how should i acquire other token ? i am using your module because it was only one i get working

**Comment by PalmEmanuel** [comment]
I don't know exactly how the EXO module works, so unless I can get another working token to compare with I can't figure out if there's a problem with AzAuth.

Maybe you can get better help if you post an issue with the EXO module?

**Comment by GamerClassN7** [comment]
> I don't know exactly how the EXO module works, so unless I can get another working token to compare with I can't figure out if there's a problem with AzAuth.
> 
> Maybe you can get better help if you post an issue with the EXO module?

Good Idea unfortunately i was not able to find any way how to contact the developers :(

**Comment by PalmEmanuel** [comment]
Without knowing what scopes the EXO module needs, I don't see how I can help you get the right token unfortunately.

I see two options if you can't find a way to report the issue:

1. Look at how the EXO module source code is built and figure out how the token is requested, then imitate that process and compare that token with what you're getting from AzAuth.
2. Use a browser and inspect your cookies for a token if you're able to do the same operations from there, then decode the token and compare it with what you're getting from AzAuth.

**Comment by GamerClassN7** [comment]
> Without knowing what scopes the EXO module needs, I don't see how I can help you get the right token unfortunately.
> 
> I see two options if you can't find a way to report the issue:
> 
> 1. Look at how the EXO module source code is built and figure out how the token is requested, then imitate that process and compare that token with what you're getting from AzAuth.
> 2. Use a browser and inspect your cookies for a token if you're able to do the same operations from there, then decode the token and compare it with what you're getting from AzAuth.

Will try to do tank you for your advice
