### ISSUE TITLE
An error when I run Get-AzToken for the first time after installation

### ISSUE THREAD

**Issue by alexandair** [PalmEmanuel/AzAuth#7]
After installing the module, I ran `Get-AzToken` for the first time and got an error.
I'm already authenticated to Azure in that PowerShell session.
```
Get-AzToken: The ChainedTokenCredential failed due to an unhandled exception: Azure PowerShell authentication timed out.
```

**Comment by PalmEmanuel** [comment]
Thanks for the bug report, I'll see if I can reproduce it! I had some weird cases when jumping between credentials and connections but didn't hit any errors during my last tests, so I thought it might have been corrected with some other code rewrites. Evidently not 😁

**Comment by alexandair** [comment]
I ran it again with the `-Debug` switch to see If I can provide more details, and this time it worked without any problems.

**Comment by PalmEmanuel** [comment]
Tricky, but good to know for where to start looking!

**Comment by PalmEmanuel** [comment]
@alexandair I'm having trouble replicating the error, which version of the Az PowerShell (Az and Az.Accounts respectively) module are you using?

**Comment by alexandair** [comment]
I've missed your reply last week.
I cannot repro either.
If it happens again, I'll let you know.
