### ISSUE TITLE
Add data to output object

### ISSUE THREAD

**Issue by bjompen** [PalmEmanuel/AzAuth#8]
If I am connected to different environments using Azure PowerShell and az login there is no simple way of knowing which of these connections are used to check out my token. 

![image](https://user-images.githubusercontent.com/17783007/232846606-aff3d62c-25e7-458a-934f-d336b6d77db4.png)
![image](https://user-images.githubusercontent.com/17783007/232846833-b08572f7-6c9d-4099-946e-df8290c98bbb.png)

Would it be possible to add more data to the returned token, such as source of the token? I know it is strictly ordered and I can find it in the source code, but it would simplify cashing of tokens and decrease the chances of working against wrong environment.

**Comment by PalmEmanuel** [comment]
That's a good idea. I'll see if I can automatically find something useful, or if we need to ad an optional string input that gets embedded in the output object or similar. I'd like to avoid taking other dependencies to parse the JWT if it's not needed, but we'll see what the options are.
