### ISSUE TITLE
Implement -Timeout

### ISSUE THREAD

**Issue by JustinGrote** [PalmEmanuel/AzAuth#86]
A Timeout option would be helpful, for instance not hanging on managed identity if it is not available or responding and move on to the other options. This is natively supported in `Azure.Identity` and just needs to be passed through to `ClientOptions`

**Comment by PalmEmanuel** [comment]
Makes sense for sure, thanks for the suggestion!

**Comment by PalmEmanuel** [comment]
`TimeoutSeconds` is already implemented for the other interactive flows, but not `-ManagedIdentity`. After doing some experimentation it seems that the `ManagedIdentityCredential` fully ignores all configuration and `ClientOptions` that has to do with delays or timeouts, so I'll likely have to implement it myself (which is also doable).

Some reading (which states that it should be improved but that's not my experience with it atm):
https://github.com/Azure/azure-sdk-for-net/issues/29471

Might also reconsider and use the default credential.
